app/dashboard/urls.py
from django.urls import path

from app.dashboard.views import dashboard_view
from app.dashboard.views import create_customer
from app.dashboard.views import get_customer
from app.dashboard.views import get_api_response

from app.dashboard.views import customer_view
from app.dashboard.views import customer_feature_handler

app_name = "dashboard"

urlpatterns = [
    path("", view=dashboard_view, name="dashboard"),
    path("get-api-response/<slug:customer_slug>/", view=get_api_response, name="get-api-response"),
    path("customer/<slug:customer_slug>/", view=customer_view, name="customer"),
    path("create-customer/", view=create_customer, name="create-customer"),
    path("get-customer/<slug:customer_slug>/", view=get_customer, name="get-customer"),
    path("customer-feature-handler/<slug:customer_slug>/", view=customer_feature_handler, name="customer-feature-hander"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("app.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("dashboard/", include("app.dashboard.urls")),
    path("features/", include("app.features.urls")),
    path("excel/", include("app.ms_graph.urls")),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token, name="obtain_auth_token"),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

app/templates/snippets/sidepanel/add_feature_to_customer.html
<div class="site-sidepanel-wrapper">
    <div class="site-sidepanel-header">
    <div>
    <h3>Choose a Workbook</h3>
    </div>
    </div>
    <div class="site-sidepanel-body">
    <form 
        hx-post="{% url 'dashboard:customer-feature-hander' customer_slug=customer_slug %}"  
        hx-swap="none" 
        hx-headers='{"x-step": "1", "x-feature": "feature_1"}'
        method="post">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
            
            <div class="mb-3">
                <label for="name" class="form-label">Workbook</label>
                <select id="workbook-select" class="workbook-select" name="workbook-select">
                    {% for workbook in workbooks %}
                        <option value="{{workbook.id}}">{{workbook.name}}</option>
                    {% endfor %}
                </select>
            </div>

            
            <div class="actions d-flex">        <div>
            <a 
                hx-delete="{% url 'dashboard:customer-feature-hander' customer_slug=customer_slug %}" 
                hx-swap="none"
                hx-target="closest #site-sidepanel"
                class="mt-3 me-3 btn btn-secondary" 
                href="javascript:void(0)">close</a>
            </div>
                <button type="submit" class="btn btn-primary mt-3">Next</button>
            </div>
        </form>
    </div>
    <div class="site-sidepanel-footer"></div>
</div>

app/templates/snippets/sidepanel/add_feature_to_customer_step_2.html
<div class="site-sidepanel-wrapper">
    <div class="site-sidepanel-header">
    <div>
    <h3>Choose a Worksheet</h3>
    </div>
    </div>
    <div class="site-sidepanel-body">
    <form 
        hx-post="{% url 'dashboard:customer-feature-hander' customer_slug=customer_slug %}"  
        hx-swap="none" 
        hx-headers='{"x-step": "2", "x-feature": "feature_1"}'
        method="post">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
            
            <div class="mb-3">
                <label for="name" class="form-label">Worksheet</label>
                <select id="worksheet-select" class="worksheet-select" name="worksheet-select">
                    {% for worksheet in worksheets %}
                        <option value="{{worksheet.id}}">{{worksheet.name}}</option>
                    {% endfor %}
                </select>
            </div>

            
            <div class="actions d-flex">        <div>
            <a 
                hx-delete="{% url 'dashboard:customer-feature-hander' customer_slug=customer_slug %}" 
                hx-swap="none"
                hx-target="closest #site-sidepanel"
                class="mt-3 me-3 btn btn-secondary" 
                href="javascript:void(0)">close</a>
            </div>
                <button type="submit" class="btn btn-primary mt-3">Next</button>
            </div>
        </form>
    </div>
    <div class="site-sidepanel-footer"></div>
</div>

app/templates/snippets/sidepanel/add_feature_to_customer_step_3.html
<div class="site-sidepanel-wrapper">
    <div class="site-sidepanel-header">
    <div>
    <h3>worksheet analysis</h3>
    </div>
    </div>
    <div class="site-sidepanel-body">
        <div class="my-4">
            <strong>headers</strong> {{headers}}
        </div>
        <div class="my-4">
            <strong>dimensions</strong> {{dimensions}}
        </div>
        <div class="my-4">
            <strong>Last Row</strong> {{last_row}}
        </div>
    <form 
        hx-post="{% url 'dashboard:customer-feature-hander' customer_slug=customer_slug %}"  
        hx-swap="none" 
        hx-headers='{"x-step": "3", "x-feature": "feature_1"}'
        method="post">
            <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
            
            
            <div class="actions d-flex">       
                <div>
                    <a 
                        hx-delete="{% url 'dashboard:customer-feature-hander' customer_slug=customer_slug %}" 
                        hx-swap="none"
                        hx-target="closest #site-sidepanel"
                        class="mt-3 me-3 btn btn-secondary" 
                        href="javascript:void(0)">close</a>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Turn On</button>
            </div>
        </form>
    </div>
    <div class="site-sidepanel-footer"></div>
</div>

app/templates/snippets/sidepanel/create_customer_action.html
<div class="site-sidepanel-wrapper">
    <div class="site-sidepanel-header">
    <div>
    <h3>Create Customer</h3>
    </div>
    </div>
    <div class="site-sidepanel-body">
    <form 
        hx-post="{% url 'dashboard:create-customer' %}"  
        hx-swap="none" 
        method="post">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

        <div class="mb-3">
            <label for="name" class="form-label">Customer Name</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>

        <div class="mb-3">
            <label for="domain" class="form-label">Domain</label>
            <input type="url" class="form-control" id="domain" name="domain" required>
        </div>

        <div class="mb-3">
            <label for="hubspot_portal_id" class="form-label">HubSpot Portal ID</label>
            <input type="text" class="form-control" id="hubspot_portal_id" name="hubspot_portal_id">
        </div>

        <!-- Collapsible Section for Integration Keys -->
        <p>
            <a class="btn btn-outline-secondary btn-sm" data-bs-toggle="collapse" href="#integrationKeys" role="button" aria-expanded="false" aria-controls="integrationKeys">
                Show Integration Keys
            </a>
        </p>
        <div class="collapse" id="integrationKeys">
            <div class="card card-body">
                <div class="mb-3">
                    <label for="hubspot_secret_app_key" class="form-label">HubSpot Secret App Key</label>
                    <input type="text" class="form-control" id="hubspot_secret_app_key" name="hubspot_secret_app_key">
                </div>

                <div class="mb-3">
                    <label for="hubspot_client_secret" class="form-label">HubSpot Client Secret</label>
                    <input type="text" class="form-control" id="hubspot_client_secret" name="hubspot_client_secret">
                </div>

                <div class="mb-3">
                    <label for="msgraph_site_id" class="form-label">MS Graph Site ID</label>
                    <input type="text" class="form-control" id="msgraph_site_id" name="msgraph_site_id">
                </div>

                <div class="mb-3">
                    <label for="msgraph_drive_id" class="form-label">MS Graph Drive ID</label>
                    <input type="text" class="form-control" id="msgraph_drive_id" name="msgraph_drive_id">
                </div>

                <div class="mb-3">
                    <label for="msgraph_client_id" class="form-label">MS Graph Client ID</label>
                    <input type="text" class="form-control" id="msgraph_client_id" name="msgraph_client_id">
                </div>

                <div class="mb-3">
                    <label for="msgraph_client_secret" class="form-label">MS Graph Client Secret</label>
                    <input type="text" class="form-control" id="msgraph_client_secret" name="msgraph_client_secret">
                </div>

                <div class="mb-3">
                    <label for="msgraph_client_id" class="form-label">MS Graph Tenant ID</label>
                    <input type="text" class="form-control" id="msgraph_tenant_id" name="msgraph_tenant_id">
                </div>

                <div class="mb-3">
                    <label for="msgraph_authority" class="form-label">MS Graph Authority</label>
                    <input type="text" class="form-control" id="msgraph_authority" name="msgraph_authority">
                </div>

                <div class="mb-3">
                    <label for="msgraph_scopes" class="form-label">MS Graph Scopes</label>
                    <input type="text" class="form-control" id="msgraph_scopes" name="msgraph_scopes">
                </div>
            </div>
        </div>
        <div class="actions d-flex">
        <div>
        <a 
            hx-delete="{% url 'dashboard:create-customer' %}" 
            hx-swap="none"
            hx-target="closest #site-sidepanel"
            class="mt-3 me-3 btn btn-secondary" 
            href="javascript:void(0)">close</a>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Save Customer</button>
        </div>
    </form>
    </div>
    <div class="site-sidepanel-footer"></div>
</div>

app/templates/snippets/sidepanel/edit_customer.html
<div class="site-sidepanel-wrapper">
  <div class="site-sidepanel-header">
    <div>
      <h3>Edit Customer</h3>
    </div>
  </div>

  <div class="site-sidepanel-body">
    <form 
      hx-post="{% url 'dashboard:get-customer' customer_slug=customer.slug %}" 
      hx-swap="none" 
      method="post">
      <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

      <div class="mb-3">
        <label for="name" class="form-label">Customer Name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ customer.name }}" required>
      </div>

      <div class="mb-3">
        <label for="domain" class="form-label">Domain</label>
        <input type="url" class="form-control" id="domain" name="domain" value="{{ customer.domain }}" required>
      </div>

      <div class="mb-3">
        <label for="hubspot_portal_id" class="form-label">HubSpot Portal ID</label>
        <input type="text" class="form-control" id="hubspot_portal_id" name="hubspot_portal_id" value="{{ customer.hubspot_portal_id }}">
      </div>

      <p>
        <a class="btn btn-outline-secondary btn-sm" data-bs-toggle="collapse" href="#integrationKeys" role="button" aria-expanded="false" aria-controls="integrationKeys">
          Show Integration Keys
        </a>
      </p>

      <div class="collapse" id="integrationKeys">
        <div class="card card-body">
          <div class="mb-3">
            <label for="hubspot_secret_app_key" class="form-label">HubSpot Secret App Key</label>
            <input type="text" class="form-control" id="hubspot_secret_app_key" name="hubspot_secret_app_key" value="{{ customer.hubspot_secret_app_key }}">
          </div>

          <div class="mb-3">
              <label for="hubspot_client_secret" class="form-label">HubSpot Client Secret</label>
              <input type="text" class="form-control" id="hubspot_client_secret" name="hubspot_client_secret" value="{{ customer.hubspot_client_secret }}">
          </div>

          <div class="mb-3">
            <label for="msgraph_site_id" class="form-label">MS Graph Site ID</label>
            <input type="text" class="form-control" id="msgraph_site_id" name="msgraph_site_id" value="{{ customer.msgraph_site_id }}">
          </div>

          <div class="mb-3">
            <label for="msgraph_drive_id" class="form-label">MS Graph Drive ID</label>
            <input type="text" class="form-control" id="msgraph_drive_id" name="msgraph_drive_id" value="{{ customer.msgraph_drive_id }}">
          </div>

          <div class="mb-3">
            <label for="msgraph_client_id" class="form-label">MS Graph Client ID</label>
            <input type="text" class="form-control" id="msgraph_client_id" name="msgraph_client_id" value="{{ customer.msgraph_client_id }}">
          </div>

          <div class="mb-3">
            <label for="msgraph_client_secret" class="form-label">MS Graph Client Secret</label>
            <input type="text" class="form-control" id="msgraph_client_secret" name="msgraph_client_secret" value="{{ customer.msgraph_client_secret }}">
          </div>

          <div class="mb-3">
            <label for="msgraph_tenant_id" class="form-label">MS Graph Tenant ID</label>
            <input type="text" class="form-control" id="msgraph_tenant_id" name="msgraph_tenant_id" value="{{ customer.msgraph_tenant_id }}">
          </div>

          <div class="mb-3">
            <label for="msgraph_authority" class="form-label">MS Graph Authority</label>
            <input type="text" class="form-control" id="msgraph_authority" name="msgraph_authority" value="{{ customer.msgraph_authority }}">
          </div>

          <div class="mb-3">
            <label for="msgraph_scopes" class="form-label">MS Graph Scopes</label>
            <input type="text" class="form-control" id="msgraph_scopes" name="msgraph_scopes" value="{{ customer.msgraph_scopes }}">
          </div>
        </div>
      </div>

      <div class="actions d-flex">
        <a 
          hx-get="{% url 'dashboard:get-customer' customer_slug=customer.slug %}" 
          hx-swap="outerHTML"
          class="mt-3 me-3 btn btn-secondary" 
          href="javascript:void(0)">cancel</a>

        <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
      </div>
    </form>
  </div>
</div>

app/templates/snippets/sidepanel/function_test_response.html
<div class="site-sidepanel-wrapper">
  <div class="site-sidepanel-header">
    <div>
      <h3>{{title}}</h3>
    </div>
  </div>
  <div class="site-sidepanel-body">
<pre id="jsonOutput" class="bg-light rounded border overflow-auto">
{{json_data_to_display|safe}}
</pre>
  </div>
    <div class="actions site-sidepanel-footer">
    <a 
      hx-delete="{% url 'dashboard:get-api-response' customer_slug=customer_slug %}" 
      hx-swap="none"
      hx-target="closest #site-sidepanel"
      class="mt-3 me-3 btn btn-secondary" 
      href="javascript:void(0)">close</a>
</div>

app/templates/snippets/sidepanel/view_customer.html
<div class="site-sidepanel-wrapper">
  <div class="site-sidepanel-header">
    <div>
      <h3>Customer Details</h3>
    </div>
  </div>

  <div class="site-sidepanel-body">
    <div class="mb-3">
      <label class="form-label">Customer Name</label>
      <div class="form-control-plaintext">{{ customer.name }}</div>
    </div>

    <div class="mb-3">
      <label class="form-label">Domain</label>
      <div class="form-control-plaintext">{{ customer.domain }}</div>
    </div>

    <div class="mb-3">
      <label class="form-label">HubSpot Portal ID</label>
      <div class="form-control-plaintext">{{ customer.hubspot_portal_id }}</div>
    </div>

    <p>
      <a class="btn btn-outline-secondary btn-sm" data-bs-toggle="collapse" href="#integrationKeys" role="button" aria-expanded="false" aria-controls="integrationKeys">
        Show Integration Keys
      </a>
    </p>

    <div class="collapse" id="integrationKeys">
      <div class="card card-body">
        <div class="mb-3">
          <label class="form-label">HubSpot Secret App Key</label>
          <div class="form-control-plaintext">{{ customer.hubspot_secret_app_key }}</div>
        </div>

        <div class="mb-3">
          <label class="form-label">HubSpot Client Secret</label>
          <div class="form-control-plaintext">{{ customer.hubspot_client_secret }}</div>
        </div>

        <div class="mb-3">
          <label class="form-label">MS Graph Site ID</label>
          <div class="form-control-plaintext">{{ customer.msgraph_site_id }}</div>
        </div>

        <div class="mb-3">
          <label class="form-label">MS Graph Drive ID</label>
          <div class="form-control-plaintext">{{ customer.msgraph_drive_id }}</div>
        </div>

        <div class="mb-3">
          <label class="form-label">MS Graph Client ID</label>
          <div class="form-control-plaintext">{{ customer.msgraph_client_id }}</div>
        </div>

        <div class="mb-3">
          <label class="form-label">MS Graph Client Secret</label>
          <div class="form-control-plaintext">{{ customer.msgraph_client_secret }}</div>
        </div>


        <div class="mb-3">
          <label class="form-label">MS Graph Tenant ID</label>
          <div class="form-control-plaintext">{{ customer.msgraph_tenant_id }}</div>
        </div>

        <div class="mb-3">
          <label class="form-label">MS Graph Authority</label>
          <div class="form-control-plaintext">{{ customer.msgraph_authority }}</div>
        </div>

        <div class="mb-3">
          <label class="form-label">MS Graph Scopes</label>
          <div class="form-control-plaintext">{{ customer.msgraph_scopes }}</div>
        </div>
      </div>
    </div>
  </div>

  <div class="actions site-sidepanel-footer">
    <a 
      hx-delete="{% url 'dashboard:get-customer' customer_slug=customer.slug %}" 
      hx-swap="none"
      hx-target="closest #site-sidepanel"
      class="mt-3 me-3 btn btn-secondary" 
      href="javascript:void(0)">close</a>

      <a 
      hx-put="{% url 'dashboard:get-customer' customer_slug=customer.slug %}" 
      hx-swap="none"
      class="mt-3 me-3 btn btn-info" 
      href="javascript:void(0)">edit</a>
  </div>
</div>